general.import = ["/home/fernando/.config/alacritty/sel.toml"]

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
# size = 14.0
size = 16.0
# size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
# family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"

[window]
opacity = 1
# opacity = 0.9

[window.dimensions]
columns = 80
lines = 30
