[colors.bright]
black = "#6e6a86"
blue = "#9ccfd8"
cyan = "#ea9a97"
green = "#3e8fb0"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.cursor]
cursor = "#ea9a97"
text = "#232136"

[colors.dim]
black = "#6e6a86"
blue = "#eb6f92"
cyan = "#3e8fb0"
green = "#f6c177"
magenta = "#9ccfd8"
red = "#c4a7e7"
white = "#ea9a97"
yellow = "#e0def4"

[colors.normal]
black = "#393552"
blue = "#9ccfd8"
cyan = "#ea9a97"
green = "#3e8fb0"
magenta = "#c4a7e7"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.primary]
background = "#232136"
dim_foreground = "#908caa"
foreground = "#e0def4"

[colors.search.matches]
background = "#ea9a97"
foreground = "CellBackground"

[colors.selection]
background = "#44415a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#ea9a97"
text = "#232136"
