prompt_name = "  Master "
pretty_name = [
    "⏻ Shutdown",
    " Reboot",
    "Z Suspend",
    " Logout",
    " Lock",
    "󱋆 Display",
    " App",
    "󰂚 Notifications",
    " Emoji",
    "󰎈 Media",
    "󱄄 Fix Display Color",
    "󰊖 Toggle Gamemode",
    "󰸉 Toggle Live Wallpaper",
    "󰐎 Play-Pause Live Wallpaper",
    "󱊷 Switch esc & caps key"
]
command = [
    "systemctl poweroff",
    "systemctl reboot",
    "loginctl lock-session && systemctl suspend",
    "~/.config/hypr/scripts/logout.sh",
    "loginctl lock-session",
    "~/Documents/Programming/shell/wlr-display.sh",
    "rofi -show drun",
    "~/.config/sway/script/notif-history",
    "~/.config/sway/script/emoji.sh",
    "~/.config/hypr/scripts/media-play-pause -p",
    "~/.config/hypr/scripts/display-color.sh",
    "~/.config/hypr/scripts/gamemode.sh",
    "~/.config/hypr/scripts/livewp.sh",
    "~/.config/hypr/scripts/livewp.sh toggle",
    "~/.config/hypr/scripts/change-caps.sh -r"
]
