prompt_name = "  Master "
pretty_name = ["⏻ Shutdown", " Reboot", "Z Suspend", " Logout", " Lock", " set display to 1080p", " set display to 720p"]
command = ["systemctl poweroff", "systemctl reboot",  "systemctl suspend", "swaymsg exit",  "~/.config/sway/script/lock.sh", "swaymsg output eDP-1 resolution 1920x1080", "swaymsg output eDP-1 resolution 1280x720"]
