# wm - use wallpaper color as the accent
accent1      = "7b8ab2"
# accent1      = "ebbcba"
accent2      = "00faf9"
# accent2      = "31748f"
inactive     = "6e6a86"
gradrotation = "45deg"
round        = "0"
gtextcolor   = "000000"
wallpaper    = "~/Downloads/ff1.png"

bgcolor        = "191724"
fgcolor        = "e0def4"
t_surface      = "1f1d2e"
t_cur_color    = "ebbcba"
t_fgcolor      = "191724"
t_fgcolor_dim  = "908caa"
t_select_color = "56526e"

t_b_black   = "6e6a86"
t_b_red     = "eb6f92"
t_b_green   = "31748f"
t_b_yellow  = "f6c177"
t_b_blue    = "9ccfd8"
t_b_magenta = "c4a7e7"
t_b_cyan    = "ebbcba"
t_b_white   = "e0def4"

t_d_black   = "6e6a86"
t_d_red     = "eb6f92"
t_d_green   = "31748f"
t_d_yellow  = "f6c177"
t_d_blue    = "9ccfd8"
t_d_magenta = "c4a7e7"
t_d_cyan    = "ebbcba"
t_d_white   = "e0def4"

t_n_black   = "403d52"
t_n_red     = "eb6f92"
t_n_green   = "31748f"
t_n_yellow  = "f6c177"
t_n_blue    = "9ccfd8"
t_n_magenta = "c4a7e7"
t_n_cyan    = "ebbcba"
t_n_white   = "e0def4"
