accent = "A7C080"
black0 = "2D353B"
black1 = "3D484D"
black2 = "4F585E"
black3 = "7A8478"
blue = "7FBBB3"
blue_dark = "7FBBB3"
cyan = "83C092"
cyan_dark = "83C092"
green = "A7C080"
green_dark = "A7C080"
magenta = "D699B6"
magenta_dark = "D699B6"
red_dark = "E67E80"
red = "E67E80"
wallpaper_path = "/home/fernando/Pictures/Random/Wallpaper/everforest2.jpg"
white0 = "D3C6AA"
white1 = "baae96"
white2 = "a09682"
white3 = "877f6d"
yellow_dark = "DBBC7F"
yellow = "DBBC7F"
